# Week 11

[**Notebook from this week**](week11_notebook.ipynb)
[**Weekly Digest 9**](../../digests/digest_9.md)

<br/>

## Quiz 10: Tuesday, April 7, 2026

Quiz 10 will be given during the class on Tuesday. Here is a [sample quiz](../../_static/quizzes/quiz10_sample.pdf).
If you have any questions about the sample quiz, I will go over them before the real quiz on Tuesday.

<br/>

**What is covered:**

- `enumerate`
- `Counter`
- list sorting

## Word frequencies

```
https://cdn.jsdelivr.net/gh/bbadzioch/mth337_site@main/schedule/week11/word_freqs.csv
```

## Generative Markov Chains

In [ ]:
import random
from time import sleep

def markov_writer(prompt, ngrams, num_sentences=1):
    print(prompt)
    n = len(next(iter(ngrams)))
    context = prompt[-n:]

    ns = 0
    while True:
        sleep(0.05)
        if context not in ngrams:
            break
        else:
            letter = random.choice(ngrams[context])
            print(letter, end="")
            context = context[1:] + letter
            if letter in ".?!":
                ns += 1
                if ns == num_sentences:
                    break

## Pandas

### Solar system planets

In [7]:
names = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"]

data = {"diameter_km": [4879, 12104, 12756, 6792, 142984, 120536, 51118, 49528, 2370],
        "avg_temp_C": [167, 464, 15, -65, -110, -140, -195, -200, -225],
        "gravity": [3.7, 8.9, 9.8, 3.7, 23.1, 9.0, 8.7, 11.0, 0.7]
        }

### Airports data

```
https://cdn.jsdelivr.net/gh/bbadzioch/mth337_site@main/schedule/week11/airports.csv
```

### Airports plot

In [ ]:
from bokeh.models import HoverTool, OpenURL, TapTool


myhover = HoverTool(tooltips= [('Name: ', '@name'),
                               ('Type: ', '@type'),
                               ("Wikipedia: ", "@wikipedia_link")])

TOOLS = ['crosshair', 'wheel_zoom', 'box_zoom', 'reset', 'box_select', 'pan', myhover, 'tap']

#get Buffalo airport data
buf = df[df['name'].str.contains("Buffalo Niagara")].iloc[0]
#get coordinates of the Buffalo airport
buf_x = buf['x']
buf_y = buf['y']
radius = 50000

p = bk.figure(width=750,
              height=500,
              x_axis_type="mercator",
              y_axis_type="mercator",
              x_range=(buf_x - radius, buf_x + radius),
              y_range=(buf_y - radius, buf_y + radius),
              tools=TOOLS)

taptool = p.select(type=TapTool)
url = "@wikipedia_link"
taptool.callback = OpenURL(url=url)

p.add_tile("CartoDB Positron", retina=True)
p.scatter(x='x', y='y', size=10, source = df, color='red', alpha=0.5)
bk.show(p)

## Regular expressions

```
https://www.gutenberg.org/cache/epub/5658/pg5658.txt
```

## Exercises

All exercises below use data on passengers of Titanic. A DataFrame with this data can be created as follows:

In [2]:
import seaborn as sns

df = sns.load_dataset("titanic")
df.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### Exercise 1

Create a DataFrame with records of all males.

**Check:** The DataFrame should consist of 577 rows.

In [6]:
df[df["sex"] == "male"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

### Exercise 2

Create a DataFrame with records of all males who survived the sinking of Titanic.

**Check:** The DataFrame should consist of 109 rows.

In [7]:
df[(df["sex"] == "male") & (df["alive"] == "yes")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
55,1,1,male,NaN,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
838,1,3,male,32.0,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
839,1,1,male,NaN,0,0,29.7000,C,First,man,True,C,Cherbourg,yes,True
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
869,1,3,male,4.0,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

### Exercise 3

Find the age of the oldest Titanic passenger.

**Check:** You should get 80.

In [11]:
df["age"].max()

80.0

### Exercise 4

Get the record of the oldest passenger.

**Check:** The passenger was a male, embarked in Southampton, traveled in the first class and survived.

In [9]:
n = df["age"].idxmax()
df.iloc[n]

survived                 1
pclass                   1
sex                   male
age                   80.0
sibsp                    0
parch                    0
fare                  30.0
embarked                 S
class                First
who                    man
adult_male            True
deck                     A
embark_town    Southampton
alive                  yes
alone                 True
Name: 630, dtype: object

### Exercise 5

Get the record of the oldest female who did not survive.

**Check:** Check: She was 57, embarked in Southampton and traveled in the second class.

In [28]:
df2 = df[(df["sex"] == "female") & (df["alive"] == "no")]
n = df2["age"].idxmax()
df2.loc[n]

survived                 0
pclass                   2
sex                 female
age                   57.0
sibsp                    0
parch                    0
fare                  10.5
embarked                 S
class               Second
who                  woman
adult_male           False
deck                     E
embark_town    Southampton
alive                   no
alone                 True
Name: 772, dtype: object

### Exercise 6

What was the average age of people who survived?

**Check:** 28.34 years.

In [29]:
df[df["alive"] == "yes"]["age"].mean()

np.float64(28.343689655172415)

<br/><br/>